name: celebrate_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2
  stack: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
