name: celebrate_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.0
  dartz: ^0.10.1
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2
  screenshot: ^3.0.0
  stack: ^0.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
